resolver: lts-7.12
packages:
- location: ../convoluted
   #git: https://github.com/jonascarpay/convoluted.git
   #commit: ae3b5ce106f213c8ad555e51002a293a22e5709f
  #extra-dep: true
- '.'
extra-deps:
flags: {}
extra-package-dbs: []
extra-include-dirs:
extra-lib-dirs:
