resolver: lts-7.12
packages:
- location: ../convoluted
   #git: https://github.com/jonascarpay/convoluted.git
   #commit: 03af796c95db5f69f5959ee78d9dff13a927c7c1
  extra-dep: true
- '.'
extra-deps:
flags: {}
extra-package-dbs: []
extra-include-dirs:
extra-lib-dirs:
