resolver: lts-7.12
packages:
- location:
   git: https://github.com/jonascarpay/convoluted.git
   commit: a5f8ef63161670f73fb95d00a0c169535ea6585f
  extra-dep: true
- '.'
extra-deps:
flags: {}
extra-package-dbs: []
extra-include-dirs:
extra-lib-dirs:
